input:
  path: 'subtitles/'

  sentence:
    ending:
      re:
        - '.'
        - '?'
        - '!'
        - ';'

    starting:
      re:
        - '>>'
        - '<<'

    remove:
      re:
        - '>>'

output:
  path:  'article/'
